# Project
project.name = "Corpus des Deutschen Bundesrechts"
project.short = "C-DBR"


# License
license.data = "Creative Commons Zero 1.0 Universal"
license.code = "MIT-0"


# Digital Object Identifier (DOI)
doi.data.concept = "10.5281/zenodo.3832111" # checked
doi.data.version = "???"

doi.software.concept = "10.5281/zenodo.4072934" # checked
doi.software.version = "???"


# Debugging

debug.toggle = "TRUE"   # Ob Debugging aktiv ist; Möglichkeiten sind "TRUE" oder "FALSE"
debug.sample = 100      # Die Anzahl der zufällig ausgewählten Rechtsakte, die im Debugging-Modus berücksichtigt werden sollen.
qa.sample = 100        # Die Anzahl der zufällig ausgewählten Einzelnormen, die zur Überprüfung separat gespeichert werden sollen.


# Parallelization

cores.max = "TRUE"  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "TRUE" oder "FALSE"
cores.number = "16"   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "FAlSE" steht


# Download
download.timeout = 600			# Timeout für Downloads


# Quanteda
quanteda.tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden


# Knitr
fig.format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
fig.dpi = 300     	 	# Auflösung für Diagramme
fig.align = "center"    	# Ausrichtung von Diagrammen im Compilation Report


# Frequenztabellen: Liste zu prüfender Variablen
#' **Hinweis:** Nur diese Variablen werden bei der Erstellung der Frequenztabellen berücksichtigt.

freqtable.ignore =  ["periodikum",
		    "fundstellentyp",
		    "check_neuf",
		    "check_aufh",
		    "check_sonst",
		    "check_hinweis",
		    "check_stand",
		    "gliederungskennzahl",
		    "ausfertigung_jahr",
		    "doi_concept",
		    "doi_version",
		    "version",	
		    "lizenz" ]
