[project]

fullname = "Corpus des Deutschen Bundesrechts"
shortname = "C-DBR"
author = "Seán Fobbe"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"



[doi] # Digital Object Identifier

data.concept = "10.5281/zenodo.3832111" # do not change
data.version = "???" # 

software.concept = "10.5281/zenodo.4072934" # do not change
software.version = "???" # 



[debug]

toggle = false   # Ob Debugging aktiv ist; Möglichkeiten sind "TRUE" oder "FALSE"
sample = 500      # Die Anzahl der zufällig ausgewählten Rechtsakte, die im Debugging-Modus berücksichtigt werden sollen.
qaSample = 50        # Die Anzahl der zufällig ausgewählten Einzelnormen, die zur Überprüfung separat gespeichert werden sollen.

cleanrun = false # Löscht vor jedem Run alle gespeicherten Zwischen- und Endergebnisse (Hinweis: ist unabhängig von debug.toggle, aber idR für Debugging nützlich)


[cores]

max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "TRUE" oder "FALSE"
number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "FAlSE" steht



[parallel]

htmlLandingPages = true
downloadXML = true
parseEinzelnormen = false # Parallelisierung instabil und kaum schneller als sequentielle Ausführung
parseMeta = false # Parallelisierung instabil und kaum schneller als sequentielle Ausführung
parseNetworks = false # Parallelisierung instabil und kaum schneller als sequentielle Ausführung
lingsummarize = true
downloadPDF = true
extractPDF = true
downloadEPUB = true
multihashes = true



[download]

timeout = 10			# Timeout für Downloads



[quanteda]

tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



[fig] # Knitr

format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
dpi = 300     	 	# Auflösung für Diagramme
align = "center"    	# Ausrichtung von Diagrammen im Compilation Report
