# This script will delete all data and targets generated by the data set creation process. Run if you want to do a hard reset before a fresh rerun.


## Remove {targets} objects
targets::tar_destroy(ask = FALSE)
targets::tar_unscript()

## Delete Manifest
standard <- c("files/",
              "temp/",
              "analysis/",
              "output/",
              "_targets.R",
              "_targets_r",
              "temp_tesseract")

custom <- c("netzwerke")

logfiles <- list.files(pattern = "\\.log")

ocrfiles <- list.files(pattern = "\\.tiff")

## Execute Delete
delete <- c(standard, custom, logfiles, ocrfiles)
unlink(delete, recursive = TRUE)
