# This script will delete all data and targets generated by the data set creation process. Run if you wish to do a hard reset for a fresh rerun.


## Remove {targets} objects
targets::tar_destroy(ask = FALSE)
targets::tar_unscript()

## Delete Manifest
standard <- c("files/",
              "temp/",
              "analysis/",
              "output/",
              "_targets.R")

custom <- c("netzwerke")

logfiles <- list.files(pattern = "\\.log")


## Execute Delete
delete <- c(standard, custom, logfiles)
unlink(delete, recursive = TRUE)
