version: "3.7"

services:
  c-dbr:
    container_name: c-dbr
    image: c-dbr:4.4.0
    tty: true
    volumes:
      - .:/c-dbr
      - ./etc/gitconfig:/etc/gitconfig
    environment:
      - TZ=Europe/Berlin