version: "3.7"

services:
  c-dbr:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: c-dbr
    image: c-dbr
    tty: true
    tmpfs: /tmp
    volumes:
      - .:/c-dbr
      - ./etc/gitconfig:/etc/gitconfig
    environment:
      - TZ=Europe/Berlin